version: '3.8'

networks:
  network:
    driver: bridge

services:
  tgbot:
    build: ./code
    container_name: tgbot
    ports:
      - "8000:8000"
    environment:
      TGTOKEN: "${TGTOKEN}"
    depends_on:
      - postgresdb
    restart: always
    networks:
      - network


  postgresdb:
    image: postgres:latest
    container_name: postgres
    build:
      context: ./database
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5433:5432"
    restart: always
    networks:
      - network